version: '3'
services:

  router:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"

  cache:
    image: redis:latest
    ports:
      - "6379:6379"

  spring-app:
    build:
      context: ./backEnd/springbootWithDocker
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST:-db}:3306/mydb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_REDIS_HOST=cache
      - SPRING_REDIS_PORT=6379